build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0-alpine
  variables:
    NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget
  cache:
    paths:
      - .nuget/
      - src/UI/App/.pnpm-store/
  script:
    - apk update && apk add nodejs-current npm
    - corepack enable && corepack prepare pnpm@latest --activate
    - dotnet build -c Release Helveg.sln
    - dotnet pack --no-build Helveg.sln -o artifacts -c Release
    - if [ "$CI_COMMIT_BRANCH" != "develop" ]; then return 0; fi
    - dotnet nuget update source ci 
      --source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"
      --username gitlab-ci-token
      --password $CI_JOB_TOKEN
      --store-password-in-clear-text
    - dotnet nuget push "artifacts/*.nupkg" --source ci
