build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
  variables:
    NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget
  cache:
    paths:
      - .nuget/
      - .pnpm-store/
  artifacts:
    paths:
      - artifacts/*.nupkg
    expire_in: 42s
  script:
    - apk update && apk add nodejs-current npm
    - dotnet tool restore

    - corepack enable && corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store/
    - pnpm install -w
    - pnpm run git-version
    - pnpm run build

    - dotnet build -c Release -p:AllowGitVersion=true Helveg.sln
    - dotnet pack --no-build -p:AllowGitVersion=true Helveg.sln -o artifacts -c Release
    - if [ "$CI_COMMIT_BRANCH" != "develop" ]; then return 0; fi
    - dotnet nuget update source ci 
      --source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"
      --username gitlab-ci-token
      --password $CI_JOB_TOKEN
      --store-password-in-clear-text
    - rm -rf artifacts/Helveg.Playground.*
    - dotnet nuget push "artifacts/*.nupkg" --source ci

publish:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
  script:
    - dotnet nuget push "artifacts/*.nupkg" --source nuget.org --api-key $NUGET_API_KEY
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
      when: always
  