build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0-alpine
  variables:
    NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget
  cache:
    paths:
      - .nuget/
      - src/UI/App/.pnpm-store/
  script:
    - apk update && apk add nodejs-current npm
    - corepack enable && corepack prepare pnpm@latest --activate
    - dotnet build -c Release Helveg.sln
    - dotnet pack src/CommandLine -o artifacts -c Release
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"
      -name gitlab
      -username gitlab-ci-token
      -password $CI_JOB_TOKEN
    - dotnet nuget push "artifacts/helveg*.nupkg" --source gitlab
