stages:
  - prebuild
  - build
  # Tests? Where we're going, we don't need tests.
  - deploy

build-windows:
  image: cafstep/helveg-ci:windows
  stage: prebuild
  script:
    - 'c:/BuildTools/Common7/Tools/Launch-VsDevShell.ps1'
    # Urgh.
    # https://stackoverflow.com/questions/2124753/how-can-i-use-powershell-with-the-visual-studio-command-prompt
    - 'cmd /c "c:/BuildTools/VC/Auxiliary/Build/vcvars64.bat&set" | foreach {
        if ($_ -match "=") {
          $v = $_.split("="); set-item -force -path "ENV:\$($v[0])" -value "$($v[1])"
        }
      }'
    - '& ./build.ps1'
  cache:
    paths:
      - build/_deps
  artifacts:
    paths:
      - artifacts/
  tags:
    - office-windows
  only:
    - master
    - /^v0\.\d+\.\d+$/

build-linux:
  dependencies:
    - build-windows
  image: cafstep/helveg-ci
  stage: build
  script:
    - ./build.sh --install --pack
  cache:
    paths:
      - build/_deps
  artifacts:
    paths:
      - artifacts/
  only:
    - master

build-linux-tag:
  dependencies:
    - build-windows
  image: cafstep/helveg-ci
  stage: build
  script:
    - ./build.sh --install --pack --tag-version
  cache:
    paths:
      - build/_deps
  artifacts:
    paths:
      - artifacts/
  only:
    - /^v0\.\d+\.\d+$/

deploy-nuget:
  dependencies:
    - build-windows
    - build-linux-tag
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  stage: deploy
  script:
    - dotnet nuget push ./artifacts/helveg*.nupkg --source nuget.org --api-key $NUGET_API_KEY
  only:
    - /^v0\.\d+\.\d+$/
