build-windows:
  image: cafstep/helveg-ci:windows
  stage: build
  script:
    - '& c:/BuildTools/Common7/Tools/Launch-VsDevShell.ps1'
    - './build.ps1'
  cache:
    paths:
      - build/_deps
  artifacts:
    paths:
      - artifacts/
  only:
    - ci

windows-linux:
  dependencies:
    - build-windows
  image: cafstep/helveg-ci
  stage: build
  script:
    - ./build.sh --install --pack
  cache:
    paths:
      - build/_deps
  artifacts:
    paths:
      - artifacts/
  only:
    - ci

    