stages:
  - prebuild
  - build

build-windows:
  image: cafstep/helveg-ci:windows
  stage: prebuild
  script:
    - '& c:/BuildTools/Common7/Tools/Launch-VsDevShell.ps1'
    - '& ./build.ps1'
  cache:
    paths:
      - build/_deps
  artifacts:
    paths:
      - artifacts/
  tags:
    - office-windows
  only:
    - ci

build-linux:
  dependencies:
    - build-windows
  image: cafstep/helveg-ci
  stage: build
  script:
    - ./build.sh --install --pack
  cache:
    paths:
      - build/_deps
  artifacts:
    paths:
      - artifacts/
  only:
    - ci

    