using System.Collections.Immutable;
using System.Text.Json.Serialization;

namespace Helveg.Visualization;

public partial class DataModel
{
    
    // TODO: Find a way to export these publicly form the autogenerated file. This is dumb.
    public static readonly ImmutableArray<JsonConverter> Converters = ImmutableArray.Create<JsonConverter>(
        MultigraphCommentFormatConverter.Singleton,
        MultigraphDiagnosticSeverityConverter.Singleton,
        new DateOnlyConverter(),
        new TimeOnlyConverter(),
        IsoDateTimeOffsetConverter.Singleton
    );
}
