// <auto-generated />
// from schema\data.json

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Helveg.Visualization.DataModel;

public class HelvegData
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("createdOn")]
	public string CreatedOn { get; set; }
	[JsonPropertyName("analyzer")]
	public AnalyzerMetadata Analyzer { get; set; }
	[JsonPropertyName("data")]
	public Multigraph Data { get; set; }
}
public class AnalyzerMetadata
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("version")]
	public string Version { get; set; }
}
public class Multigraph
{
	[JsonPropertyName("nodes")]
	public Dictionary<string, MultigraphNode> Nodes { get; set; }
	[JsonPropertyName("relations")]
	public Dictionary<string, MultigraphRelation> Relations { get; set; }
}
public class MultigraphNode
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("kind")]
	public string Kind { get; set; }
	[JsonPropertyName("diagnostics")]
	public MultigraphDiagnostic[] Diagnostics { get; set; }
}
public class MultigraphRelation
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("isTransitive")]
	public bool IsTransitive { get; set; }
	[JsonPropertyName("edges")]
	public MultigraphEdge[] Edges { get; set; }
}
public class MultigraphDiagnostic
{
	[JsonPropertyName("id")]
	public string Id { get; set; }
	[JsonPropertyName("severity")]
	public string Severity { get; set; }
	[JsonPropertyName("message")]
	public string Message { get; set; }
}
public class MultigraphEdge
{
	[JsonPropertyName("src")]
	public string Src { get; set; }
	[JsonPropertyName("dst")]
	public string Dst { get; set; }
}

