// <auto-generated />
// from schema\data.json

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Helveg.Visualization.DataSchema;

public class HelvegData
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("createdOn")]
	public string CreatedOn { get; set; }
	[JsonPropertyName("analyzer")]
	public AnalyzerMetadata Analyzer { get; set; }
	[JsonPropertyName("data")]
	public Multigraph Data { get; set; }
}
public class AnalyzerMetadata
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("version")]
	public string Version { get; set; }
}
public class Multigraph
{
	[JsonPropertyName("nodes")]
	public Dictionary<string, Node> Nodes { get; set; }
	[JsonPropertyName("relations")]
	public Dictionary<string, Relation> Relations { get; set; }
}
public class Node
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("kind")]
	public string Kind { get; set; }
}
public class Relation
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("isTransitive")]
	public bool IsTransitive { get; set; }
	[JsonPropertyName("edges")]
	public Edge[] Edges { get; set; }
}
public class Edge
{
	[JsonPropertyName("src")]
	public string Src { get; set; }
	[JsonPropertyName("dst")]
	public string Dst { get; set; }
}

