// <auto-generated />
// from schema\icon-set.json

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Helveg.Visualization.IconSetModel;

public class HelvegIconSet
{
	[JsonPropertyName("namespace")]
	public string Namespace { get; set; }
	[JsonPropertyName("icons")]
	public Icon[] Icons { get; set; }
}
public class Icon
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
	[JsonPropertyName("format")]
	public string Format { get; set; }
	[JsonPropertyName("data")]
	public string Data { get; set; }
}

