using System;
using System.CommandLine;
using System.IO;
using System.Threading.Tasks;
using Json.Schema;
using Json.Schema.CodeGeneration;
using Json.Schema.CodeGeneration.Language;

namespace Helveg.Engineering.JsonSchemaGenerator;

public static class Program
{
    public static async Task<int> Main(string[] args)
    {
        var rootCmd = new RootCommand("Generate POCOs from a JSON schema.");

        var schemaArg = new Argument<FileInfo>("schema");
        rootCmd.Add(schemaArg);

        var outputArg = new Argument<string>("output");
        rootCmd.Add(outputArg);
        
        var namespaceArg = new Argument<string>("namespace");
        rootCmd.Add(namespaceArg);
        
        rootCmd.SetHandler(GeneratePocos, schemaArg, outputArg, namespaceArg);
        return await rootCmd.InvokeAsync(args);
    }

    public static async Task GeneratePocos(FileInfo schemaPath, string outputPath, string @namespace)
    {
        var schema = JsonSchema.FromFile(schemaPath.FullName);
        var generatedCode = schema.GenerateCode(CodeWriters.CSharp);
        using var stream = new FileStream(outputPath, FileMode.Create, FileAccess.ReadWrite, FileShare.None);
        using var writer = new StreamWriter(stream);
        await writer.WriteLineAsync(
$@"// <auto-generated />
// from {Path.GetRelativePath(Environment.CurrentDirectory, schemaPath.FullName)}

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace {@namespace};
");
        await writer.WriteLineAsync(generatedCode);
    }
}
